#!/usr/bin/env python

from __future__ import print_function
import sys

def fill(t, typearg=""):
    return """
    public static {targs} void fill({t}[] buffer, {t} value) {{
        int size = buffer.length - 1;
        int cleared = 1;
        int index = 1;
        buffer[0] = value;
        while (cleared < size) {{
            System.arraycopy(buffer, 0, buffer, index, cleared);
            size -= cleared;
            index += cleared;
            cleared <<= 1;
        }}
        System.arraycopy(buffer, 0, buffer, index, size);
    }}
    """.format(t=t, targs="<{}>".format(typearg) if typearg else "")

gen = fill("int") + fill("float") + fill("T", "T")

print(sys.stdin.read().replace("/* {AUTOGENERATED CODE HERE} */", gen))
